---
kind: pipeline
type: docker
name: build & release

steps:
  - name: build
    image: node
    environment:
      REACT_APP_PLAID_PUBLIC_KEY:
        from_secret: plaid_public_key
      REACT_APP_PLAID_PRODUCT_SCOPE:
        from_secret: plaid_scope
      REACT_APP_PLAID_ENVIRONMENT:
        from_secret: plaid_env
      REACT_APP_AWS_REGION:
        from_secret: aws_region
      REACT_APP_AWS_USER_POOL_ID:
        from_secret: pool_id
      REACT_APP_AWS_USER_POOL_WEB_CLIENT_ID:
        from_secret: pool_client_id
      FONTAWESOME_NPM_AUTH_TOKEN:
        from_secret: font_awesome_token
      REACT_APP_API_ENDPOINT:
        from_secret: graphql_endpoint
    commands:
      - yarn
      - yarn run build
  - name: release
    image: hashicorp/terraform
    environment:
      TF_CLOUD_TOKEN:
        from_secret: tf_cloud_token
      TFVARS:
        from_secret: tfvars
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION:
        from_secret: aws_region
      SERVICE_ACCOUNT:
        from_secret: service_account
    commands:
      - echo "$SERVICE_ACCOUNT" >> ./service-account.json
      - echo "$TFVARS" >> ./terraform.tfvars
      - terraform init -backend-config="token=$TF_CLOUD_TOKEN"
      - terraform apply -auto-approve=true

trigger:
  branch:
    - master
