version: 0.2

phases:
  install:
    commands:
      - curl -fsSLO "https://releases.hashicorp.com/terraform/0.13.6/terraform_0.13.6_linux_amd64.zip"
      - unzip terraform_0.13.6_linux_amd64.zip -d /usr/local/bin
  pre_build:
    commands:
      - touch .npmrc
      - echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
      - echo "//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}" >> .npmrc
      - yarn
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - terraform init -backend-config="token=$TF_CLOUD_TOKEN"
      - terraform apply -auto-approve -input=false
