version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ff_admin
      MONGO_INITDB_ROOT_PASSWORD: money

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ff_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: money
