name: Build Web
on:
  - push
  - pull_request

jobs:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v1.2.0
      with:
        version: 4.11.1
        run_install: |
          - args: [--filter, web]
